add e2e to CircleCI config  and a make clean as well
CircleCI reported this error:

    cmd/manager/main.go:194:11: undefined: metrics.ExposeMetricsPort

I suspect it is used a cached operator-sdk v0.9.0. Hopefully andding a
`make clean` resolves the error.